<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNGV6iH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNGV6iH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNGV6iH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNGV6iH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXNGV6iH\App_KernelDevDebugContainer([
    'container.build_hash' => 'XNGV6iH',
    'container.build_id' => 'a3613912',
    'container.build_time' => 1707555714,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNGV6iH');
